project:
  type: website
  output-dir: docs

excute:
  freeze: auto

website: 
  bread-crumbs: false
  back-to-top-navigation: true
  title: "KDSC"
  navbar:
    background: light
    logo: kdsc_logo.png
    logo-alt: "KDSC logo"
    title: false
    collapse-below: lg
    left:
      - text: Home
        file: index.qmd
      - sidebar:about_us
      - sidebar:projects
      - sidebar:curriculum
    tools:
      - icon: buildings
        menu: 
          - text: KDSC website
            url: https://data.ku.edu/kdsc
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/KansasData
          - text: Report Bug
            url: https://github.com/KansasData
    
  sidebar: 
    - id: about_us
      title: "About us"
      style: "docked"
      background: light
      foreground: dark
      collapse-level: 2
      contents: 
        - text: "Who We Are"
          href: about_us.qmd
        - text: "People"
          href: people.qmd
        
    - id: projects
      title: "Project"
      style: "docked"
      collapse-level: 2
      contents: 
        - project.qmd
        - dataset.qmd
        
    - id: curriculum
      title: "Curriculum"
      style: "docked"
      contents:
        - curriculum.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

