project:
  type: website
  resources:
    - CNAME
  output-dir: docs

website: 
  bread-crumbs: false
  back-to-top-navigation: true
  title: "KDSC"
  navbar:
    background: light
    logo: kdsc_logo.png
    logo-alt: "KDSC logo"
    title: false
    collapse-below: lg
    left:
      - text: "Home"
        href: index.qmd
      - text: "Community Data Lab"
        href: project.qmd
      - text: "Curriculum"
        href: competency.qmd
    tools:
      - icon: buildings
        menu: 
          - text: KDSC website
            url: https://data.ku.edu/kdsc
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/KansasData
          - text: Report Bug
            url: https://github.com/KansasData
  sidebar:
    - id: curriculum
      title: "Curriculum"
      collapse-level: 1
      contents:
        - text: "Competency"
          href: competency.qmd
        - text: "Course"
          href: course.qmd
        - text: "Module"
          href: module.qmd
  page-footer:
    left: |
      Proudly supported by 
      [![NSF image](NSF.png){width=150}](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2148878)
    right: |
    
      [![](arise_logo.png){width=60}](https://nsfepscor.ku.edu/track-1-arise/)

    center: | 
          Except where otherwise noted content on this site is </br> licensed under a [CC BY-NC](https://creativecommons.org/licenses/by-nc/4.0/deed.en)</br>
  site-url: https://datarepository.ku.edu
  repo-url: https://github.com/kansasdata/repo

format:
  html:
    grid: 
      sidebar-width: 150px
      body-width: 900px
      margin-width: 200px
      gutter-width: 1.5rem
    theme: cosmo
    css: styles.css
    toc: true
