project:
  type: website
  output-dir: docs
excute:
  freeze: auto
website: 
  title: "KDSC"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about_us.qmd
      - project.qmd
      - curriculum.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
