project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website: 
  bread-crumbs: false
  back-to-top-navigation: true
  title: "KDSC"
  navbar:
    background: light
    logo: kdsc_logo.png
    logo-alt: "KDSC logo"
    title: false
    collapse-below: lg
    
    left:
      - text: "Home"
        href: index.qmd
      - text: "Community Data Lab"
        href: project.qmd
      - text: "Curriculum"
        href: curriculum.qmd
      - text: "ARISE Data"
        href: ARISE/arise.qmd
  
    tools:
      - icon: buildings
        menu: 
          - text: KDSC website
            url: https://data.ku.edu/kdsc
      - icon: github
        menu:
          - text: Report Bug
            url: https://github.com/KansasData/repo/issues

          
  page-footer:
    left: |
      Proudly supported by 
      [![NSF image](/images/NSF.png){width=150}](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2148878)
    right: |
    
      [![](/images/arise_logo.png){width=60}](https://nsfepscor.ku.edu/track-1-arise/)

    center: | 
          Except where otherwise noted content on this site is </br> licensed under a [CC BY-NC](https://creativecommons.org/licenses/by-nc/4.0/deed.en)</br>
  site-url: https://datarepository.ku.edu
  repo-url: https://github.com/KansasData/repo


format:
  html:
    grid:
      body-width: 1000px
      margin-width: 150px
      gutter-width: 1.5rem
    theme: cosmo
    css: styles.css
    toc: true
    anchor-sections: false
editor: visual

