project:
  type: website
  output-dir: docs

excute:
  freeze: auto

website: 
  bread-crumbs: false
  back-to-top-navigation: true
  title: "KDSC"
  navbar:
    background: light
    logo: kdsc_logo.png
    logo-alt: "KDSC logo"
    title: false
    collapse-below: lg
    left:
      - text: Home
        file: index.qmd
      - sidebar:projects
      - sidebar:curriculum
    tools:
      - icon: buildings
        menu: 
          - text: KDSC website
            url: https://data.ku.edu/kdsc
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/KansasData
          - text: Report Bug
            url: https://github.com/KansasData
    
  sidebar: 
    - id: projects
      title: "Community Data Lab"
      style: "docked"
      collapse-level: 2
      contents: 
        - text: "Project"
          href: project.qmd
        - text: "Dataset"
          href: dataset.qmd
        
    - id: curriculum
      title: "Curriculum"
      style: "docked"
      contents:
        - text: "Competency"
          href: competency.qmd
        - text: "Course"
          href: course.qmd
        - text: "Module"
          href: module.qmd
  
  page-footer:
    left: | 
      Proudly supported by 
      [![NSF image](NSF.png){width=200}](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2148878)
    right: |
    
      [![](arise_logo.png){width=100}](https://nsfepscor.ku.edu/track-1-arise/)
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

