---
title: "Welcome to KDSC’s Repository of Data Science Curriculum Materials"
toc: false
---

This website serves as an online repository for data science curriculum materials developed by the Kansas Data Science Consortium [KDSC](https://data.ku.edu/kdsc) team. Faculty from our educational partners collaborate to create open-source coursework that is adaptable to various institutions and academic majors. The repository features two primary components: the Community Data Lab and the Curriculum, both designed to support and enhance data science education.

::: content-block
### Community Data Lab Projects

The Community Data Lab is our signature program which brings real-world projects into the classroom. This section of the repository is where we house deidentified data, code, and project reports from past community data lab projects. We have also worked to build educational materials using these projects which are housed in this part of the repository. This open-source framework is designed to provide a rich array of projects suited for data science education. These projects may be used in future Community Data Labs by the KDSC or can be adapted for other data science courses.

::: learn-more
[Projects »](project.qmd)
:::

### Curriculum

Our curriculum repository contains content from a wide range of data science courses - from introductory concepts to advanced machine learning. The curriculum in our repository includes lecture materials, code, exercises, and datasets, all systematically organized . The curriculum on our repository is crafted to build essential data science skills and competencies, ensuring a comprehensive learning experience. Our modules can be implemented in a variety of educational settings to enrich and expand learners’ understanding of fundamental data science concepts.

::: learn-more
[Curriculum Repository »](competency.qmd)
:::
:::
