---
title: "Data Ethics Webinar"
source: "Lecture Material"
author: "Ramón Alvarado"
institution: "University of Oregon"
competency: [Data Wrangling, Ethical Problem Solving]
main-format: Lecture Recording
toc: true
toc-title: "On this page"
---

## Material Description

This webinar was designed to encourage students and faculty to stop and think about the ethical standards of data science. Ramón discusses three founding principles of data ethics and identifies several areas of concern when discussing bias and fairness.

Roughly a decade ago Floridi and Taddeo (2016) defined data ethics as a field that draws insights from the ethics of data (e.g., gathering, curation, storage), the ethics of algorithms (the use, deployment, and design of computational technologies) and the ethics of practice (oaths, mission statements, best- practices, etc.). A more sophisticated overview of such field could also easily identified that, despite its repeated omission from the literature, business ethics is additionally one of the most insightful sources of careful consideration and precedent for the field (De George, 2009). Underlying any and all of these sources is of course an exploration of profound moral dilemmas and frameworks which— for better or for worse— strongly hinge on utilitarian values. For the past decade, however, the strict focus of data ethics on harm mitigation related to transparency, bias, fairness, compliance, and regulation have exhausted its program without much left to show for it other than tired narratives that have lead to either ethics washing or ethics bashing (Bietti, 2020). In this talk we will explore what it means for a data ethics program to go beyond this paradigm of mitigation and start asking questions from a philosophical perspective in which data, databases, and data technologies inevitably drive the most central aspects of our contemporary civilization.

## Module Materials

```{=html}
<iframe id="kmsembed-1_0h4zx3zn" width="400" height="285" src="https://mediahub.ku.edu/embed/secure/iframe/entryId/1_0h4zx3zn/uiConfId/54254972/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Data Ethics Webinar"></iframe>
```

This Material is under the [CC BY-ND license](https://creativecommons.org/licenses/by-nd/4.0/deed.en)
